import {
    MdSchool,
    MdBusiness,
    MdPerson,
    MdArticle,
    MdCall,
    MdCampaign,
    MdShoppingCart,
    MdDashboard,
    MdHandshake,
    MdEmail,
    MdStore,
    MdReceipt,
    MdLibraryBooks,
    MdPublic,
    MdMailOutline,
    MdMeetingRoom,
    MdNotes,
    MdLocalShipping,
    MdInventory2,
    MdBarChart,
    MdChecklist,
    MdSettings,
    MdDescription,
    MdTaskAlt,
    MdSupportAgent,
    MdBuild,
    MdAutoAwesome,
} from "react-icons/md";

const MoreFilterList = [
    {
        id: 1,
        label: "Academy",
        icon: MdSchool,
        shown: true,
    },
    {
        id: 2,
        label: "Companies",
        icon: MdBusiness,
        shown: true,
    },
    {
        id: 3,
        label: "Contacts",
        icon: MdPerson,
        shown: false,
    },
    {
        id: 4,
        label: "Blog posts",
        icon: MdArticle,
        shown: true,
    },
    {
        id: 5,
        label: "Calls",
        icon: MdCall,
        shown: false,
    },
    {
        id: 6,
        label: "Campaigns",
        icon: MdCampaign,
        shown: false,
    },
    {
        id: 7,
        label: "Carts",
        icon: MdShoppingCart,
        shown: false,
    },
    {
        id: 8,
        label: "Dashboards",
        icon: MdDashboard,
        shown: false,
    },
    {
        id: 9,
        label: "Deals",
        icon: MdHandshake,
        shown: false,
    },
    {
        id: 10,
        label: "Emails",
        icon: MdEmail,
        shown: false,
    },
    {
        id: 11,
        label: "HubSpot Marketplace",
        icon: MdStore,
        shown: false,
    },
    {
        id: 12,
        label: "Invoices",
        icon: MdReceipt,
        shown: false,
    },
    {
        id: 13,
        label: "Knowledge Documents",
        icon: MdLibraryBooks,
        shown: false,
    },
    {
        id: 14,
        label: "Landing pages",
        icon: MdPublic,
        shown: false,
    },
    {
        id: 15,
        label: "Marketing emails",
        icon: MdMailOutline,
        shown: false,
    },
    {
        id: 16,
        label: "Meetings",
        icon: MdMeetingRoom,
        shown: false,
    },
    {
        id: 17,
        label: "Notes",
        icon: MdNotes,
        shown: false,
    },
    {
        id: 18,
        label: "Orders",
        icon: MdLocalShipping,
        shown: false,
    },
    {
        id: 19,
        label: "Products",
        icon: MdInventory2,
        shown: false,
    },
    {
        id: 20,
        label: "Reports",
        icon: MdBarChart,
        shown: false,
    },
    {
        id: 21,
        label: "Segments (Lists)",
        icon: MdChecklist,
        shown: false,
    },
    {
        id: 22,
        label: "Settings",
        icon: MdSettings,
        shown: false,
    },
    {
        id: 23,
        label: "Site pages",
        icon: MdDescription,
        shown: false,
    },
    {
        id: 24,
        label: "Tasks",
        icon: MdTaskAlt,
        shown: false,
    },
    {
        id: 25,
        label: "Tickets",
        icon: MdSupportAgent,
        shown: false,
    },
    {
        id: 26,
        label: "Tools",
        icon: MdBuild,
        shown: false,
    },
    {
        id: 27,
        label: "Workflows",
        icon: MdAutoAwesome,
        shown: false,
    },
];

export default MoreFilterList;